# Generated by Django 3.1.7 on 2021-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, verbose_name='лайк/дизлайк'),
        ),
    ]
