# Generated by Django 3.1.7 on 2021-03-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_question_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
    ]
