# Generated by Django 3.1.7 on 2021-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=0, verbose_name='колличество ответов'),
        ),
    ]
