# Generated by Django 3.1.7 on 2021-04-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210413_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes_user_q', to=settings.AUTH_USER_MODEL, verbose_name='id'),
        ),
    ]
