# Generated by Django 3.1.7 on 2021-04-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210413_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='id_user',
            new_name='id_user_id',
        ),
    ]
