# Generated by Django 3.1.7 on 2021-03-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_like', models.IntegerField(default=0, verbose_name='id')),
                ('id_user', models.IntegerField(default=0, verbose_name='id лайкнувшего')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=255, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=30, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='question',
            name='id_like',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.likes', verbose_name='кто лайкнул'),
            preserve_default=False,
        ),
    ]
