# Generated by Django 3.1.7 on 2021-04-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20210413_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='id_user_id',
        ),
        migrations.AddField(
            model_name='likes',
            name='id_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='id'),
            preserve_default=False,
        ),
    ]
