# Generated by Django 3.1.7 on 2021-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210309_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_like',
            field=models.IntegerField(verbose_name='кто лайкнул'),
        ),
    ]
