# Generated by Django 3.1.7 on 2021-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210309_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_like',
            field=models.IntegerField(default=0, verbose_name='кто лайкнул'),
        ),
    ]
