# Generated by Django 3.1.7 on 2021-03-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210309_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='id_like',
            new_name='id_question',
        ),
    ]
