# Generated by Django 3.1.7 on 2021-03-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210309_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_like',
        ),
    ]
